
package presentacion;

/**
 *
 * @author Valeria
 */
public class frmCartelera extends javax.swing.JFrame {

    /**
     * Creates new form frmCartelera
     */
    public frmCartelera() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnVolver = new javax.swing.JButton();
        lblTituloCartelera = new javax.swing.JLabel();
        jLPelicula4 = new javax.swing.JLabel();
        cbxCiudad = new javax.swing.JComboBox<>();
        cbxSucursal = new javax.swing.JComboBox<>();
        btnSiguiente = new javax.swing.JButton();
        jLPelicula3 = new javax.swing.JLabel();
        jLbPelicula1 = new javax.swing.JLabel();
        jLPelicula5 = new javax.swing.JLabel();
        jLbPelicula2 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        btnSeleccionar5 = new javax.swing.JButton();
        btnSeleccionar1 = new javax.swing.JButton();
        btnSeleccionar2 = new javax.swing.JButton();
        btnSeleccionar3 = new javax.swing.JButton();
        bntSeleccionar4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(58, 107, 203));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVolver.setBackground(new java.awt.Color(153, 204, 255));
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 20));

        lblTituloCartelera.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTituloCartelera.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloCartelera.setText("Cartelera");
        jPanel1.add(lblTituloCartelera, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLPelicula4.setForeground(new java.awt.Color(255, 255, 255));
        jLPelicula4.setText("Pelicula4");
        jLPelicula4.setToolTipText("");
        jLPelicula4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLPelicula4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 130, 170));

        cbxCiudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbxCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 120, 25));

        cbxSucursal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbxSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 120, 25));

        btnSiguiente.setText("Siguiente");
        jPanel1.add(btnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 390, -1, -1));

        jLPelicula3.setBackground(new java.awt.Color(204, 204, 204));
        jLPelicula3.setForeground(new java.awt.Color(255, 255, 255));
        jLPelicula3.setText("Pelicula3");
        jLPelicula3.setToolTipText("");
        jLPelicula3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLPelicula3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 130, 170));

        jLbPelicula1.setForeground(new java.awt.Color(255, 255, 255));
        jLbPelicula1.setText("Pelicula1");
        jLbPelicula1.setToolTipText("");
        jLbPelicula1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLbPelicula1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 130, 170));

        jLPelicula5.setForeground(new java.awt.Color(255, 255, 255));
        jLPelicula5.setText("Pelicula5");
        jLPelicula5.setToolTipText("");
        jLPelicula5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLPelicula5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 130, 130, 170));

        jLbPelicula2.setForeground(new java.awt.Color(255, 255, 255));
        jLbPelicula2.setText("Pelicula2");
        jLbPelicula2.setToolTipText("");
        jLbPelicula2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLbPelicula2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 130, 170));

        btnBuscar.setText("Buscar");
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 70, -1, -1));

        btnAtras.setText("Atras");
        jPanel1.add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, -1));

        btnSeleccionar5.setBackground(new java.awt.Color(255, 225, 0));
        btnSeleccionar5.setText("Seleccionar");
        jPanel1.add(btnSeleccionar5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 310, -1, -1));

        btnSeleccionar1.setBackground(new java.awt.Color(255, 225, 0));
        btnSeleccionar1.setText("Seleccionar");
        jPanel1.add(btnSeleccionar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        btnSeleccionar2.setBackground(new java.awt.Color(255, 225, 0));
        btnSeleccionar2.setText("Seleccionar");
        jPanel1.add(btnSeleccionar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, -1, -1));

        btnSeleccionar3.setBackground(new java.awt.Color(255, 225, 0));
        btnSeleccionar3.setText("Seleccionar");
        jPanel1.add(btnSeleccionar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, -1, -1));

        bntSeleccionar4.setBackground(new java.awt.Color(255, 225, 0));
        bntSeleccionar4.setText("Seleccionar");
        jPanel1.add(bntSeleccionar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        frmInicioSesionCliente regresar = new frmInicioSesionCliente();
        regresar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
   /* public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
   /*     try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCartelera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCartelera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCartelera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCartelera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
   /*     java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCartelera().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntSeleccionar4;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnSeleccionar1;
    private javax.swing.JButton btnSeleccionar2;
    private javax.swing.JButton btnSeleccionar3;
    private javax.swing.JButton btnSeleccionar5;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cbxCiudad;
    private javax.swing.JComboBox<String> cbxSucursal;
    private javax.swing.JLabel jLPelicula3;
    private javax.swing.JLabel jLPelicula4;
    private javax.swing.JLabel jLPelicula5;
    private javax.swing.JLabel jLbPelicula1;
    private javax.swing.JLabel jLbPelicula2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTituloCartelera;
    // End of variables declaration//GEN-END:variables
}
