
package presentacion;

/**
 *
 * @author Valeria
 */
public class frmCartelera extends javax.swing.JFrame {

    /**
     * Creates new form frmCartelera
     */
    public frmCartelera() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnVolverC = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLPelicula4 = new javax.swing.JLabel();
        cbxCiudad = new javax.swing.JComboBox<>();
        cbxSucursal = new javax.swing.JComboBox<>();
        btnAtras = new javax.swing.JButton();
        jLPelicula3 = new javax.swing.JLabel();
        jLbPelicula1 = new javax.swing.JLabel();
        jLPelicula5 = new javax.swing.JLabel();
        jLbPelicula2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        btnAtras1 = new javax.swing.JButton();
        btnAtras2 = new javax.swing.JButton();
        btnAtras3 = new javax.swing.JButton();
        btnAtras4 = new javax.swing.JButton();
        btnAtras5 = new javax.swing.JButton();
        btnAtras6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVolverC.setBackground(new java.awt.Color(153, 204, 255));
        btnVolverC.setText("Volver");
        btnVolverC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverCActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolverC, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 20));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cartelera");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLPelicula4.setForeground(new java.awt.Color(255, 255, 255));
        jLPelicula4.setText("Pelicula4");
        jLPelicula4.setToolTipText("");
        jLPelicula4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLPelicula4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 90, 120));

        cbxCiudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbxCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 90, -1));

        cbxSucursal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbxSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 90, -1));

        btnAtras.setText("Siguiente");
        jPanel1.add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, -1, -1));

        jLPelicula3.setBackground(new java.awt.Color(204, 204, 204));
        jLPelicula3.setForeground(new java.awt.Color(255, 255, 255));
        jLPelicula3.setText("Pelicula3");
        jLPelicula3.setToolTipText("");
        jLPelicula3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLPelicula3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 90, 120));

        jLbPelicula1.setForeground(new java.awt.Color(255, 255, 255));
        jLbPelicula1.setText("Pelicula1");
        jLbPelicula1.setToolTipText("");
        jLbPelicula1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLbPelicula1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 90, 120));

        jLPelicula5.setForeground(new java.awt.Color(255, 255, 255));
        jLPelicula5.setText("Pelicula5");
        jLPelicula5.setToolTipText("");
        jLPelicula5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLPelicula5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, 90, 120));

        jLbPelicula2.setForeground(new java.awt.Color(255, 255, 255));
        jLbPelicula2.setText("Pelicula2");
        jLbPelicula2.setToolTipText("");
        jLbPelicula2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLbPelicula2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 90, 120));

        jButton2.setText("Buscar");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, -1, -1));

        btnAtras1.setText("Atras");
        jPanel1.add(btnAtras1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, -1));

        btnAtras2.setBackground(new java.awt.Color(255, 255, 0));
        btnAtras2.setText("Seleccionar");
        jPanel1.add(btnAtras2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, -1, -1));

        btnAtras3.setBackground(new java.awt.Color(255, 255, 0));
        btnAtras3.setText("Seleccionar");
        jPanel1.add(btnAtras3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        btnAtras4.setBackground(new java.awt.Color(255, 255, 0));
        btnAtras4.setText("Seleccionar");
        jPanel1.add(btnAtras4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, -1, -1));

        btnAtras5.setBackground(new java.awt.Color(255, 255, 0));
        btnAtras5.setText("Seleccionar");
        jPanel1.add(btnAtras5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, -1, -1));

        btnAtras6.setBackground(new java.awt.Color(255, 255, 0));
        btnAtras6.setText("Seleccionar");
        jPanel1.add(btnAtras6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 380));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverCActionPerformed
        frmInicioSesionCliente regresar = new frmInicioSesionCliente();
        regresar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverCActionPerformed

    /**
     * @param args the command line arguments
     */
   /* public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
   /*     try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCartelera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCartelera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCartelera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCartelera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
   /*     java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCartelera().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnAtras1;
    private javax.swing.JButton btnAtras2;
    private javax.swing.JButton btnAtras3;
    private javax.swing.JButton btnAtras4;
    private javax.swing.JButton btnAtras5;
    private javax.swing.JButton btnAtras6;
    private javax.swing.JButton btnVolverC;
    private javax.swing.JComboBox<String> cbxCiudad;
    private javax.swing.JComboBox<String> cbxSucursal;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLPelicula3;
    private javax.swing.JLabel jLPelicula4;
    private javax.swing.JLabel jLPelicula5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLbPelicula1;
    private javax.swing.JLabel jLbPelicula2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
