/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

/**
 *
 * @author Valeria
 */
public class frmCatalogoFunciones extends javax.swing.JFrame {

    /**
     * Creates new form frmCatalogoFunciones
     */
    public frmCatalogoFunciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCatalogoFunciones = new javax.swing.JPanel();
        btnVolverFuncion = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFunciones = new javax.swing.JTable();
        btnAgregarFuncion = new javax.swing.JButton();
        btnBuscarFuncion = new javax.swing.JButton();
        btnAtrasCatFuncio = new javax.swing.JButton();
        btnSiguienteCatFuncio = new javax.swing.JButton();
        lblNumPagCatFuncio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelCatalogoFunciones.setBackground(new java.awt.Color(58, 107, 203));
        jPanelCatalogoFunciones.setPreferredSize(new java.awt.Dimension(920, 600));
        jPanelCatalogoFunciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVolverFuncion.setBackground(new java.awt.Color(153, 204, 255));
        btnVolverFuncion.setText("Volver");
        btnVolverFuncion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverFuncionActionPerformed(evt);
            }
        });
        jPanelCatalogoFunciones.add(btnVolverFuncion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 20));
        jPanelCatalogoFunciones.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 590, 25));

        jScrollPane1.setBackground(new java.awt.Color(153, 204, 255));

        jTableFunciones.setBackground(new java.awt.Color(153, 204, 255));
        jTableFunciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Tiemp. Limpieza", "Fecha", "Inicio", "Fin", "Pelicula", "Eliminar"
            }
        ));
        jScrollPane1.setViewportView(jTableFunciones);

        jPanelCatalogoFunciones.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 800, 380));

        btnAgregarFuncion.setBackground(new java.awt.Color(153, 204, 255));
        btnAgregarFuncion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAgregarFuncion.setText("Agregar");
        btnAgregarFuncion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarFuncionActionPerformed(evt);
            }
        });
        jPanelCatalogoFunciones.add(btnAgregarFuncion, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 500, 100, 30));

        btnBuscarFuncion.setBackground(new java.awt.Color(153, 204, 255));
        btnBuscarFuncion.setText("Buscar");
        jPanelCatalogoFunciones.add(btnBuscarFuncion, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 60, -1, -1));

        btnAtrasCatFuncio.setText("Atras");
        jPanelCatalogoFunciones.add(btnAtrasCatFuncio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, -1, -1));

        btnSiguienteCatFuncio.setText("Siguiente");
        jPanelCatalogoFunciones.add(btnSiguienteCatFuncio, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 550, -1, -1));

        lblNumPagCatFuncio.setText("numeroPag");
        jPanelCatalogoFunciones.add(lblNumPagCatFuncio, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 560, -1, -1));

        getContentPane().add(jPanelCatalogoFunciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverFuncionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverFuncionActionPerformed
        //        frmMetodosPagos regresar = new frmMetodosPagos();
        //        regresar.setVisible(true);
        //        this.dispose();
    }//GEN-LAST:event_btnVolverFuncionActionPerformed

    private void btnAgregarFuncionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarFuncionActionPerformed
        frmDatosPelicula agregar = new frmDatosPelicula();
        agregar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAgregarFuncionActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarFuncion;
    private javax.swing.JButton btnAtrasCatFuncio;
    private javax.swing.JButton btnBuscarFuncion;
    private javax.swing.JButton btnSiguienteCatFuncio;
    private javax.swing.JButton btnVolverFuncion;
    private javax.swing.JPanel jPanelCatalogoFunciones;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableFunciones;
    private javax.swing.JLabel lblNumPagCatFuncio;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
