package presentacion;

import dto.SucursalDTO;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import negocio.NegocioException;
import negocio.SucursalNegocio;

/**
 *
 * @author Valeria
 */
public class frmDatosSucursal extends javax.swing.JFrame {
    
    private Map<String, List<String>> ciudadesPorEstado;

    /**
     * Creates new form frmDatosSucursal
     */
    public frmDatosSucursal() {
        initComponents();
        inicializarCiudadesPorEstado();
    }
    
    private void inicializarCiudadesPorEstado() {
        ciudadesPorEstado = new HashMap<>();
        ciudadesPorEstado.put("Sonora", Arrays.asList("Hermosillo", "Nogales", "Obregón"));
        ciudadesPorEstado.put("Jalisco", Arrays.asList("Guadalajara", "Puerto Vallarta", "Tlaquepaque"));
        ciudadesPorEstado.put("Nuevo León", Arrays.asList("Monterrey", "San Nicolás", "Guadalupe"));
        // Agrega más estados y ciudades según sea necesario
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        cbxEstado = new javax.swing.JComboBox<>();
        lblNombre = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        txtNombreSucursal = new javax.swing.JTextField();
        cbxCiudad = new javax.swing.JComboBox<>();
        lblCalle = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        txtCodigoP = new javax.swing.JTextField();
        btnGuardarSucursal = new javax.swing.JButton();
        txtCalle = new javax.swing.JTextField();
        lblCiudad3 = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Datos de Sucursal");
        setMinimumSize(new java.awt.Dimension(540, 370));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(58, 107, 203));
        jPanel1.setMinimumSize(new java.awt.Dimension(540, 370));
        jPanel1.setPreferredSize(new java.awt.Dimension(540, 370));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Datos de la Sucursal");
        jPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        btnVolver.setBackground(new java.awt.Color(153, 204, 255));
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 20));

        cbxEstado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estado", "Sonora" }));
        cbxEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxEstadoActionPerformed(evt);
            }
        });
        jPanel1.add(cbxEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 260, 30));

        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("Nombre");
        jPanel1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 60, 30));

        lblEstado.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblEstado.setForeground(new java.awt.Color(255, 255, 255));
        lblEstado.setText("Estado");
        jPanel1.add(lblEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 50, 30));

        txtNombreSucursal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txtNombreSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 260, 30));

        cbxCiudad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxCiudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2" }));
        jPanel1.add(cbxCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 260, 30));

        lblCalle.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblCalle.setForeground(new java.awt.Color(255, 255, 255));
        lblCalle.setText("Calle");
        jPanel1.add(lblCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 40, 30));

        lblDireccion.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblDireccion.setForeground(new java.awt.Color(255, 255, 255));
        lblDireccion.setText("Dirección");
        jPanel1.add(lblDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 70, 30));

        txtCodigoP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txtCodigoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 260, 30));

        btnGuardarSucursal.setBackground(new java.awt.Color(153, 204, 255));
        btnGuardarSucursal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnGuardarSucursal.setText("Guardar");
        btnGuardarSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarSucursalActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardarSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, 110, 30));

        txtCalle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txtCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 260, 30));

        lblCiudad3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblCiudad3.setForeground(new java.awt.Color(255, 255, 255));
        lblCiudad3.setText("Ciudad");
        jPanel1.add(lblCiudad3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 50, 30));

        lblCodigo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblCodigo.setForeground(new java.awt.Color(255, 255, 255));
        lblCodigo.setText("Código postal");
        jPanel1.add(lblCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 100, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 430));
        jPanel1.getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        frmCatalogoSucursales regresar = new frmCatalogoSucursales();
        regresar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void cbxEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxEstadoActionPerformed
        String estadoSeleccionado = cbxEstado.getSelectedItem().toString();

        // Limpiar el JComboBox de ciudades
        cbxCiudad.removeAllItems();

        // Obtener las ciudades del estado seleccionado
        List<String> ciudades = ciudadesPorEstado.get(estadoSeleccionado);
        
        if (ciudades != null) {
            for (String ciudad : ciudades) {
                cbxCiudad.addItem(ciudad);
            }
        }
    }//GEN-LAST:event_cbxEstadoActionPerformed

    private void btnGuardarSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarSucursalActionPerformed
       
        String nombreSucursal = txtNombreSucursal.getText();
        String calle = txtCalle.getText();
        String codigoPostal = txtCodigoP.getText();
        String ciudad = cbxCiudad.getSelectedItem().toString();
        String estado = cbxEstado.getSelectedItem().toString();

        // Validación de campos vacíos
        if (nombreSucursal.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese el nombre de la sucursal.");
            return;
        }
        if (calle.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese la calle de la sucursal.");
            return;
        }
        if (codigoPostal.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese el código postal.");
            return;
        }
        if (estado.equals("Estado")) {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione un estado.");
            return;
        }
        if (ciudad.equals("Ciudad")) {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione una ciudad.");
            return;
        }

        // Crear un objeto SucursalDTO
        SucursalDTO sucursalDTO = new SucursalDTO();
        sucursalDTO.setNombre(nombreSucursal);
        sucursalDTO.setCalle(calle);
        sucursalDTO.setCodigoPostal(codigoPostal);
        sucursalDTO.setEstado(estado);
        sucursalDTO.setCiudad(ciudad);
        
        try {
            // Llamar a la capa de negocio
            SucursalNegocio sucursalNegocio = new SucursalNegocio();
            sucursalNegocio.agregarSucursal(sucursalDTO);
            JOptionPane.showMessageDialog(this, "Sucursal registrada con éxito.");
            this.setVisible(false);
            frmCatalogoSucursales catalogoSucursales = new frmCatalogoSucursales();
            catalogoSucursales.setVisible(true); // Mostrar la nueva ventana
        } catch (SQLException ex) {
            Logger.getLogger(frmDatosSucursal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGuardarSucursalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDatosSucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDatosSucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDatosSucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDatosSucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmDatosSucursal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarSucursal;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cbxCiudad;
    private javax.swing.JComboBox<String> cbxEstado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCalle;
    private javax.swing.JLabel lblCiudad3;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtCalle;
    private javax.swing.JTextField txtCodigoP;
    private javax.swing.JTextField txtNombreSucursal;
    // End of variables declaration//GEN-END:variables
}
