/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

/**
 *
 * @author Valeria
 */
public class frmHorarios extends javax.swing.JFrame {

    /**
     * Creates new form frmHorarios
     */
    public frmHorarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelHorario = new javax.swing.JPanel();
        btnVolver = new javax.swing.JButton();
        lblCine = new javax.swing.JLabel();
        lblPoster = new javax.swing.JLabel();
        btnEntradaGeneral = new javax.swing.JButton();
        btnEntadaVip = new javax.swing.JButton();
        btnContinuar = new javax.swing.JButton();
        cbxDia = new javax.swing.JComboBox<>();
        lblnformacionPeli = new javax.swing.JLabel();
        lblFuncionesVip = new javax.swing.JLabel();
        lblFuncinesGeneral = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelHorario.setBackground(new java.awt.Color(58, 107, 203));
        jPanelHorario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVolver.setBackground(new java.awt.Color(153, 204, 255));
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanelHorario.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 20));

        lblCine.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCine.setForeground(new java.awt.Color(255, 255, 255));
        lblCine.setText("Cine");
        jPanelHorario.add(lblCine, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 300, -1));

        lblPoster.setForeground(new java.awt.Color(255, 255, 255));
        lblPoster.setText("Poster");
        lblPoster.setToolTipText("");
        lblPoster.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelHorario.add(lblPoster, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 160, 200));

        btnEntradaGeneral.setBackground(new java.awt.Color(255, 225, 0));
        btnEntradaGeneral.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEntradaGeneral.setText("Entadada general");
        jPanelHorario.add(btnEntradaGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, -1, -1));

        btnEntadaVip.setBackground(new java.awt.Color(255, 225, 0));
        btnEntadaVip.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEntadaVip.setText("Entada VIP");
        btnEntadaVip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntadaVipActionPerformed(evt);
            }
        });
        jPanelHorario.add(btnEntadaVip, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, -1, -1));

        btnContinuar.setBackground(new java.awt.Color(255, 225, 0));
        btnContinuar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnContinuar.setText("Contunuar compra");
        jPanelHorario.add(btnContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, 170, 40));

        cbxDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado", "Domingo" }));
        jPanelHorario.add(cbxDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, -1, -1));

        lblnformacionPeli.setForeground(new java.awt.Color(255, 255, 255));
        lblnformacionPeli.setText("Informacion de pelicula");
        jPanelHorario.add(lblnformacionPeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        lblFuncionesVip.setForeground(new java.awt.Color(255, 255, 255));
        lblFuncionesVip.setText("Funciones");
        jPanelHorario.add(lblFuncionesVip, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, -1, -1));

        lblFuncinesGeneral.setForeground(new java.awt.Color(255, 255, 255));
        lblFuncinesGeneral.setText("Funciones");
        jPanelHorario.add(lblFuncinesGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, -1, -1));

        getContentPane().add(jPanelHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        frmCartelera regresar = new frmCartelera();
        regresar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnEntadaVipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntadaVipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEntadaVipActionPerformed

    /**
     * @param args the command line arguments
     */
 /*   public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
  /*      try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmHorarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmHorarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmHorarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmHorarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>

        /* Create and display the form */
   /*     java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmHorarios().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinuar;
    private javax.swing.JButton btnEntadaVip;
    private javax.swing.JButton btnEntradaGeneral;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cbxDia;
    private javax.swing.JPanel jPanelHorario;
    private javax.swing.JLabel lblCine;
    private javax.swing.JLabel lblFuncinesGeneral;
    private javax.swing.JLabel lblFuncionesVip;
    private javax.swing.JLabel lblPoster;
    private javax.swing.JLabel lblnformacionPeli;
    // End of variables declaration//GEN-END:variables
}
