/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

/**
 *
 * @author Valeria
 */
public class frmHorarios extends javax.swing.JFrame {

    /**
     * Creates new form frmHorarios
     */
    public frmHorarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelHorario = new javax.swing.JPanel();
        btnVolverC = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLbPoster = new javax.swing.JLabel();
        btnAtras4 = new javax.swing.JButton();
        btnAtras5 = new javax.swing.JButton();
        btnAtras6 = new javax.swing.JButton();
        jComboBoxDia = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelHorario.setBackground(new java.awt.Color(58, 107, 203));
        jPanelHorario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVolverC.setBackground(new java.awt.Color(153, 204, 255));
        btnVolverC.setText("Volver");
        btnVolverC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverCActionPerformed(evt);
            }
        });
        jPanelHorario.add(btnVolverC, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 20));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cine");
        jPanelHorario.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 300, -1));

        jLbPoster.setForeground(new java.awt.Color(255, 255, 255));
        jLbPoster.setText("Poster");
        jLbPoster.setToolTipText("");
        jLbPoster.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelHorario.add(jLbPoster, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 160, 200));

        btnAtras4.setBackground(new java.awt.Color(255, 225, 0));
        btnAtras4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAtras4.setText("Entadada general");
        jPanelHorario.add(btnAtras4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, -1, -1));

        btnAtras5.setBackground(new java.awt.Color(255, 225, 0));
        btnAtras5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAtras5.setText("Entada VIP");
        btnAtras5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtras5ActionPerformed(evt);
            }
        });
        jPanelHorario.add(btnAtras5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, -1, -1));

        btnAtras6.setBackground(new java.awt.Color(255, 225, 0));
        btnAtras6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnAtras6.setText("Contunuar compra");
        jPanelHorario.add(btnAtras6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, 170, 40));

        jComboBoxDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado", "Domingo" }));
        jPanelHorario.add(jComboBoxDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Informacion de pelicula");
        jPanelHorario.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Funciones");
        jPanelHorario.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Funciones");
        jPanelHorario.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, -1, -1));

        getContentPane().add(jPanelHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverCActionPerformed
        frmCartelera regresar = new frmCartelera();
        regresar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverCActionPerformed

    private void btnAtras5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtras5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAtras5ActionPerformed

    /**
     * @param args the command line arguments
     */
 /*   public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
  /*      try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmHorarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmHorarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmHorarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmHorarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>

        /* Create and display the form */
   /*     java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmHorarios().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras4;
    private javax.swing.JButton btnAtras5;
    private javax.swing.JButton btnAtras6;
    private javax.swing.JButton btnVolverC;
    private javax.swing.JComboBox<String> jComboBoxDia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLbPoster;
    private javax.swing.JPanel jPanelHorario;
    // End of variables declaration//GEN-END:variables
}
