package presentacion;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import persistencia.ConexionBD;
import persistencia.IConexionBD;

/**
 *
 * @author Valeria
 */
public class frmInicioSesionAdm extends javax.swing.JFrame {

    private IConexionBD conexionBD;

    /**
     * Creates new form frmInicioSesionAdm
     */
    public frmInicioSesionAdm(ConexionBD conexionBD) {
        this.conexionBD = conexionBD;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtContraseña = new javax.swing.JTextField();
        txt = new javax.swing.JTextField();
        lblTitulo = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        btnInicioSesion = new javax.swing.JButton();
        lblContraseña = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(58, 107, 203));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtContraseña.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 270, 30));

        txt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 270, 30));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Inicio Sesión");
        jPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        lblCorreo.setForeground(new java.awt.Color(255, 255, 255));
        lblCorreo.setText("Correo");
        jPanel1.add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        btnInicioSesion.setBackground(new java.awt.Color(153, 204, 255));
        btnInicioSesion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnInicioSesion.setText("Inicar sesión");
        btnInicioSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioSesionActionPerformed(evt);
            }
        });
        jPanel1.add(btnInicioSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, -1, 30));

        lblContraseña.setForeground(new java.awt.Color(255, 255, 255));
        lblContraseña.setText("Contraseña");
        jPanel1.add(lblContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioSesionActionPerformed
        String correo = txt.getText();
        String contrasena = txtContraseña.getText();

        try {
            if (verificarCredenciales(correo, contrasena)) {
                // Si las credenciales son correctas, proceder al siguiente formulario
                JOptionPane.showMessageDialog(this, "Inicio de sesión exitoso");
                frmMenu menu = new frmMenu();
                menu.setVisible(true);
                this.dispose(); // Cierra la ventana de login
            } else {
                // Mostrar error si las credenciales son incorrectas
                JOptionPane.showMessageDialog(this, "Correo o contraseña incorrectos");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al intentar iniciar sesión: " + e.getMessage());
        }

    }//GEN-LAST:event_btnInicioSesionActionPerformed
    public boolean verificarCredenciales(String correo, String contrasena) throws SQLException {
        Connection conexion = null;
        PreparedStatement ps = null;
        ResultSet rs = null;
        boolean valido = false;

        try {
            conexion = conexionBD.crearConexion(); // Tu método de conexión
            String sql = "SELECT ID, Usuario, Contrasena FROM Administradores WHERE Usuario = ? AND Contrasena = ?";
            ps = conexion.prepareStatement(sql);
            ps.setString(1, correo);
            ps.setString(2, contrasena);
            rs = ps.executeQuery();

            if (rs.next()) {
                valido = true; // Las credenciales coinciden
            }
        } catch (SQLException e) {
            e.printStackTrace();
            throw new SQLException("Error al verificar credenciales");
        } finally {
            if (rs != null) {
                rs.close();
            }
            if (ps != null) {
                ps.close();
            }
            if (conexion != null) {
                conexion.close();
            }
        }

        return valido;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmInicioSesionAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmInicioSesionAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmInicioSesionAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmInicioSesionAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        IConexionBD conexionBD = new ConexionBD();
        java.awt.EventQueue.invokeLater(new Runnable() {
             
            public void run() {
                
                new frmInicioSesionAdm((ConexionBD) conexionBD).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInicioSesion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txt;
    private javax.swing.JTextField txtContraseña;
    // End of variables declaration//GEN-END:variables

}
