/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

/**
 *
 * @author Valeria
 */
public class frmMenu extends javax.swing.JFrame {

    /**
     * Creates new form frmMenu
     */
    public frmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSucursales = new javax.swing.JButton();
        btnGenerarReportes = new javax.swing.JButton();
        btnPeliculas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(58, 107, 203));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSucursales.setBackground(new java.awt.Color(153, 204, 255));
        btnSucursales.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSucursales.setText("Sucursales");
        jPanel1.add(btnSucursales, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 220, 70));

        btnGenerarReportes.setBackground(new java.awt.Color(153, 204, 255));
        btnGenerarReportes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnGenerarReportes.setText("Generar reportes");
        jPanel1.add(btnGenerarReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 220, 70));

        btnPeliculas.setBackground(new java.awt.Color(153, 204, 255));
        btnPeliculas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPeliculas.setText("Películas");
        jPanel1.add(btnPeliculas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 220, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 410));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerarReportes;
    private javax.swing.JButton btnPeliculas;
    private javax.swing.JButton btnSucursales;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
