package presentacion;

/**
 *
 * @author Valeria
 */
public class frmMetodosPagos extends javax.swing.JFrame {

    /**
     * Creates new form frmMetodosPagos
     */
    public frmMetodosPagos() {
        setSize(300, 400);
        setResizable(false);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMetdosPago = new javax.swing.JPanel();
        btnPagoEfectivo = new javax.swing.JButton();
        btnPagoTarjeta1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Metodo de pago");

        jPanelMetdosPago.setBackground(new java.awt.Color(0, 51, 153));
        jPanelMetdosPago.setMinimumSize(new java.awt.Dimension(350, 450));
        jPanelMetdosPago.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPagoEfectivo.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnPagoEfectivo.setText("Efectivo");
        jPanelMetdosPago.add(btnPagoEfectivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 270, 90));

        btnPagoTarjeta1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnPagoTarjeta1.setText("Tarjeta de credito / Debito");
        jPanelMetdosPago.add(btnPagoTarjeta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 270, 90));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Métodos de pago");
        jPanelMetdosPago.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMetdosPago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMetdosPago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
 /*   public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
     /*   try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMetodosPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMetodosPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMetodosPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMetodosPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    /*    java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMetodosPagos().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPagoEfectivo;
    private javax.swing.JButton btnPagoTarjeta1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelMetdosPago;
    // End of variables declaration//GEN-END:variables
}
