
package presentacion;

/**
 *
 * @author Valeria
 */
public class frmOpcionReprtes extends javax.swing.JFrame {

    /**
     * Creates new form frmOpcionReprtes
     */
    public frmOpcionReprtes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnReportePeliculas = new javax.swing.JButton();
        btnReporteSucursales = new javax.swing.JButton();
        lblReportes = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(58, 107, 203));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnReportePeliculas.setBackground(new java.awt.Color(204, 204, 255));
        btnReportePeliculas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnReportePeliculas.setText("Ganancias por películas");
        btnReportePeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportePeliculasActionPerformed(evt);
            }
        });
        jPanel1.add(btnReportePeliculas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 240, 60));

        btnReporteSucursales.setBackground(new java.awt.Color(204, 204, 255));
        btnReporteSucursales.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnReporteSucursales.setText("Ganancias por sucursales");
        jPanel1.add(btnReporteSucursales, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 240, 60));

        lblReportes.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblReportes.setForeground(new java.awt.Color(255, 255, 255));
        lblReportes.setText("Reportes");
        jPanel1.add(lblReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        btnVolver.setBackground(new java.awt.Color(153, 204, 255));
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 410));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnReportePeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportePeliculasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReportePeliculasActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
//        frmInicioSesionCliente regresar = new frmInicioSesionCliente();
//        regresar.setVisible(true);
//        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReportePeliculas;
    private javax.swing.JButton btnReporteSucursales;
    private javax.swing.JButton btnVolver;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblReportes;
    // End of variables declaration//GEN-END:variables
}
