package presentacion;

/**
 *
 * @author Valeria
 */
public class frmPagoConTarjeta extends javax.swing.JFrame {

    /**
     * Creates new form frmPagoConTarjeta
     */
    public frmPagoConTarjeta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblTituloPagoConTarjeta = new javax.swing.JLabel();
        lblTotalPagoTarjeta = new javax.swing.JLabel();
        lblSubtituloTarjeta = new javax.swing.JLabel();
        lblTituloTotalEntradas = new javax.swing.JLabel();
        lblTotalEntradas = new javax.swing.JLabel();
        lblTituloTotalPagoTarjeta = new javax.swing.JLabel();
        btnVolverC1 = new javax.swing.JButton();
        btnimprimirTicket = new javax.swing.JButton();

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Toatl de entradas:");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(58, 107, 203));
        jPanel1.setMinimumSize(new java.awt.Dimension(480, 350));
        jPanel1.setPreferredSize(new java.awt.Dimension(480, 350));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloPagoConTarjeta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTituloPagoConTarjeta.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloPagoConTarjeta.setText("Tarjeta Credito / Debito");
        jPanel1.add(lblTituloPagoConTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

        lblTotalPagoTarjeta.setBackground(new java.awt.Color(255, 255, 255));
        lblTotalPagoTarjeta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTotalPagoTarjeta.setForeground(new java.awt.Color(255, 255, 255));
        lblTotalPagoTarjeta.setText("$0.00");
        lblTotalPagoTarjeta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(lblTotalPagoTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 80, -1));

        lblSubtituloTarjeta.setBackground(new java.awt.Color(255, 255, 255));
        lblSubtituloTarjeta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSubtituloTarjeta.setForeground(new java.awt.Color(255, 255, 255));
        lblSubtituloTarjeta.setText("Pago realizado con tarjeta");
        lblSubtituloTarjeta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(lblSubtituloTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));

        lblTituloTotalEntradas.setBackground(new java.awt.Color(255, 255, 255));
        lblTituloTotalEntradas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTituloTotalEntradas.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloTotalEntradas.setText("Total de entradas:");
        lblTituloTotalEntradas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(lblTituloTotalEntradas, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        lblTotalEntradas.setBackground(new java.awt.Color(255, 255, 255));
        lblTotalEntradas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTotalEntradas.setForeground(new java.awt.Color(255, 255, 255));
        lblTotalEntradas.setText("Total entradas");
        lblTotalEntradas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(lblTotalEntradas, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, -1, -1));

        lblTituloTotalPagoTarjeta.setBackground(new java.awt.Color(255, 255, 255));
        lblTituloTotalPagoTarjeta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTituloTotalPagoTarjeta.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloTotalPagoTarjeta.setText("Total:");
        lblTituloTotalPagoTarjeta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(lblTituloTotalPagoTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        btnVolverC1.setBackground(new java.awt.Color(153, 204, 255));
        btnVolverC1.setText("Volver");
        btnVolverC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverC1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolverC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 20));

        btnimprimirTicket.setBackground(new java.awt.Color(255, 255, 51));
        btnimprimirTicket.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnimprimirTicket.setText("Imprimir Ticket");
        jPanel1.add(btnimprimirTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 350));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverC1ActionPerformed
        frmMetodosPagos regresar = new frmMetodosPagos();
        regresar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverC1ActionPerformed

    /**
     * @param args the command line arguments
     */
    /*    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
 /*    try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPagoConTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPagoConTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPagoConTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPagoConTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
 /*      java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPagoConTarjeta().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolverC1;
    private javax.swing.JButton btnimprimirTicket;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblSubtituloTarjeta;
    private javax.swing.JLabel lblTituloPagoConTarjeta;
    private javax.swing.JLabel lblTituloTotalEntradas;
    private javax.swing.JLabel lblTituloTotalPagoTarjeta;
    private javax.swing.JLabel lblTotalEntradas;
    private javax.swing.JLabel lblTotalPagoTarjeta;
    // End of variables declaration//GEN-END:variables
}
