package presentacion;

/**
 *
 * @author Valeria
 */
public class frmPagoEnEfectivo extends javax.swing.JFrame {

    /**
     * Creates new form frmPagoEnEfectivo
     */
    public frmPagoEnEfectivo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTituloPagoEfectivo = new javax.swing.JLabel();
        lblTotalEfectivo = new javax.swing.JLabel();
        lblSubtituloPagoEfectivo = new javax.swing.JLabel();
        lblTitulototalEntradasEfect = new javax.swing.JLabel();
        lblTotalEntradasEfect = new javax.swing.JLabel();
        lblTituloTotalEfectivo = new javax.swing.JLabel();
        btnVolverC1 = new javax.swing.JButton();
        btnGenerarQR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(58, 107, 203));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloPagoEfectivo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTituloPagoEfectivo.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloPagoEfectivo.setText("Efectivo");
        jPanel1.add(lblTituloPagoEfectivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, -1));

        lblTotalEfectivo.setBackground(new java.awt.Color(255, 255, 255));
        lblTotalEfectivo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTotalEfectivo.setForeground(new java.awt.Color(255, 255, 255));
        lblTotalEfectivo.setText("$0.00");
        lblTotalEfectivo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(lblTotalEfectivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 120, -1));

        lblSubtituloPagoEfectivo.setBackground(new java.awt.Color(255, 255, 255));
        lblSubtituloPagoEfectivo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSubtituloPagoEfectivo.setForeground(new java.awt.Color(255, 255, 255));
        lblSubtituloPagoEfectivo.setText("Pago realizado con efectivo");
        lblSubtituloPagoEfectivo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(lblSubtituloPagoEfectivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

        lblTitulototalEntradasEfect.setBackground(new java.awt.Color(255, 255, 255));
        lblTitulototalEntradasEfect.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTitulototalEntradasEfect.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulototalEntradasEfect.setText("Total de entradas:");
        lblTitulototalEntradasEfect.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(lblTitulototalEntradasEfect, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        lblTotalEntradasEfect.setBackground(new java.awt.Color(255, 255, 255));
        lblTotalEntradasEfect.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTotalEntradasEfect.setForeground(new java.awt.Color(255, 255, 255));
        lblTotalEntradasEfect.setText("Total entradas");
        lblTotalEntradasEfect.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(lblTotalEntradasEfect, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, -1, -1));

        lblTituloTotalEfectivo.setBackground(new java.awt.Color(255, 255, 255));
        lblTituloTotalEfectivo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTituloTotalEfectivo.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloTotalEfectivo.setText("Total:");
        lblTituloTotalEfectivo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(lblTituloTotalEfectivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        btnVolverC1.setBackground(new java.awt.Color(153, 204, 255));
        btnVolverC1.setText("Volver");
        btnVolverC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverC1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolverC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 20));

        btnGenerarQR.setBackground(new java.awt.Color(255, 255, 102));
        btnGenerarQR.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnGenerarQR.setText("Generar QR");
        jPanel1.add(btnGenerarQR, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverC1ActionPerformed
        frmMetodosPagos regresar = new frmMetodosPagos();
        regresar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverC1ActionPerformed

    /**
     * @param args the command line arguments
     */
    /*   public static void main(String args[]) {
        /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
 /*    try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPagoEnEfectivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPagoEnEfectivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPagoEnEfectivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPagoEnEfectivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
 /*   java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPagoEnEfectivo().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerarQR;
    private javax.swing.JButton btnVolverC1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblSubtituloPagoEfectivo;
    private javax.swing.JLabel lblTituloPagoEfectivo;
    private javax.swing.JLabel lblTituloTotalEfectivo;
    private javax.swing.JLabel lblTitulototalEntradasEfect;
    private javax.swing.JLabel lblTotalEfectivo;
    private javax.swing.JLabel lblTotalEntradasEfect;
    // End of variables declaration//GEN-END:variables
}
