
package presentacion;

/**
 *
 * @author Valeria
 */
public class frmRegistroCliente extends javax.swing.JFrame {

    /**
     * Creates new form frmRegistroCliente
     */
    public frmRegistroCliente() {
        setSize(600, 380);
        setResizable(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RegistroCliente = new javax.swing.JPanel();
        txtApMaterno = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtApPaterno = new javax.swing.JTextField();
        txtNumCelular = new javax.swing.JTextField();
        txtConfContraseña = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JTextField();
        txtFechaNacimiento = new javax.swing.JTextField();
        btnVolver = new javax.swing.JButton();
        btnRegistrarse = new javax.swing.JButton();
        jLaberRegistro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro");
        setName("Registro"); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RegistroCliente.setBackground(new java.awt.Color(0, 51, 153));
        RegistroCliente.setMinimumSize(new java.awt.Dimension(500, 340));
        RegistroCliente.setPreferredSize(new java.awt.Dimension(500, 340));
        RegistroCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtApMaterno.setBackground(new java.awt.Color(0, 51, 153));
        txtApMaterno.setForeground(new java.awt.Color(255, 255, 255));
        txtApMaterno.setText("Apellido materno");
        txtApMaterno.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 204, 255), 2, true));
        txtApMaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApMaternoActionPerformed(evt);
            }
        });
        RegistroCliente.add(txtApMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 170, 30));

        txtCorreo.setBackground(new java.awt.Color(0, 51, 153));
        txtCorreo.setForeground(new java.awt.Color(255, 255, 255));
        txtCorreo.setText("Correo");
        txtCorreo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 204, 255), 2, true));
        RegistroCliente.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 170, 30));

        txtApPaterno.setBackground(new java.awt.Color(0, 51, 153));
        txtApPaterno.setForeground(new java.awt.Color(255, 255, 255));
        txtApPaterno.setText("Apellido paterno");
        txtApPaterno.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 204, 255), 2, true));
        txtApPaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApPaternoActionPerformed(evt);
            }
        });
        RegistroCliente.add(txtApPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 170, 30));

        txtNumCelular.setBackground(new java.awt.Color(0, 51, 153));
        txtNumCelular.setForeground(new java.awt.Color(255, 255, 255));
        txtNumCelular.setText("Numero celular");
        txtNumCelular.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 204, 255), 2, true));
        RegistroCliente.add(txtNumCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 170, 30));

        txtConfContraseña.setBackground(new java.awt.Color(0, 51, 153));
        txtConfContraseña.setForeground(new java.awt.Color(255, 255, 255));
        txtConfContraseña.setText("Confirmar contraseña");
        txtConfContraseña.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 204, 255), 2, true));
        RegistroCliente.add(txtConfContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 170, 30));

        txtNombre.setBackground(new java.awt.Color(0, 51, 153));
        txtNombre.setForeground(new java.awt.Color(255, 255, 255));
        txtNombre.setText("Nombre");
        txtNombre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 204, 255), 2, true));
        RegistroCliente.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 170, 30));

        txtContraseña.setBackground(new java.awt.Color(0, 51, 153));
        txtContraseña.setForeground(new java.awt.Color(255, 255, 255));
        txtContraseña.setText("Contraseña");
        txtContraseña.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 204, 255), 2, true));
        RegistroCliente.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 170, 30));

        txtFechaNacimiento.setBackground(new java.awt.Color(0, 51, 153));
        txtFechaNacimiento.setForeground(new java.awt.Color(255, 255, 255));
        txtFechaNacimiento.setText("Fecha de nacimiento");
        txtFechaNacimiento.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 204, 255), 2, true));
        RegistroCliente.add(txtFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 170, 30));

        btnVolver.setBackground(new java.awt.Color(153, 204, 255));
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        RegistroCliente.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 20));

        btnRegistrarse.setBackground(new java.awt.Color(153, 204, 255));
        btnRegistrarse.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRegistrarse.setText("Registrarse");
        btnRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarseActionPerformed(evt);
            }
        });
        RegistroCliente.add(btnRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 120, 30));

        jLaberRegistro.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLaberRegistro.setForeground(new java.awt.Color(255, 255, 255));
        jLaberRegistro.setText("Registro");
        RegistroCliente.add(jLaberRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, -1, -1));

        getContentPane().add(RegistroCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 380));
        RegistroCliente.getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtApMaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApMaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApMaternoActionPerformed

    private void txtApPaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApPaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApPaternoActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        frmInicioSesionCliente regresar = new frmInicioSesionCliente();
        regresar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarseActionPerformed

    /**
     * @param args the command line arguments
     */
  //  public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
     /*   try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRegistroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRegistroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRegistroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRegistroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
     /*   java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRegistroCliente().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel RegistroCliente;
    private javax.swing.JButton btnRegistrarse;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLaberRegistro;
    private javax.swing.JTextField txtApMaterno;
    private javax.swing.JTextField txtApPaterno;
    private javax.swing.JTextField txtConfContraseña;
    private javax.swing.JTextField txtContraseña;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtFechaNacimiento;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumCelular;
    // End of variables declaration//GEN-END:variables
}
