
package presentacion;

/**
 *
 * @author Valeria
 */
public class frmResumenCompra extends javax.swing.JFrame {

    /**
     * Creates new form frmResumenCompra
     */
    public frmResumenCompra() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        DatosPelicula = new javax.swing.JPanel();
        jLInicio = new javax.swing.JLabel();
        jLabelTotalResumenCompra = new javax.swing.JLabel();
        jLabelHoraFin = new javax.swing.JLabel();
        jLFin = new javax.swing.JLabel();
        jLPeli = new javax.swing.JLabel();
        jLabelPelicula = new javax.swing.JLabel();
        jLabelTipoEntrada = new javax.swing.JLabel();
        jLabelHoraInicio = new javax.swing.JLabel();
        jLEntrada = new javax.swing.JLabel();
        jLTotal = new javax.swing.JLabel();
        btnMetodoPago = new javax.swing.JButton();
        btnVolverC1 = new javax.swing.JButton();
        jLbPelicula1 = new javax.swing.JLabel();
        infPelicula = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Resumen de compra");
        setBackground(new java.awt.Color(0, 51, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(58, 107, 203));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Resumen de compra");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, -1));

        DatosPelicula.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        DatosPelicula.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLInicio.setText("Horario inicio:");
        DatosPelicula.add(jLInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 80, 25));

        jLabelTotalResumenCompra.setText("Total");
        DatosPelicula.add(jLabelTotalResumenCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 70, 25));

        jLabelHoraFin.setText("Fin");
        DatosPelicula.add(jLabelHoraFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 120, 25));
        jLabelHoraFin.getAccessibleContext().setAccessibleName("Pelicula");

        jLFin.setText("Horario fin:");
        DatosPelicula.add(jLFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 60, 25));

        jLPeli.setText("Película: ");
        DatosPelicula.add(jLPeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 50, 25));

        jLabelPelicula.setText("Pelicula");
        DatosPelicula.add(jLabelPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 120, 25));

        jLabelTipoEntrada.setText("Entrada");
        DatosPelicula.add(jLabelTipoEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 120, 25));

        jLabelHoraInicio.setText("Inicio");
        DatosPelicula.add(jLabelHoraInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 120, 25));

        jLEntrada.setText("Tipo de entrada:");
        DatosPelicula.add(jLEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 90, 25));

        jLTotal.setText("Costo total: ");
        DatosPelicula.add(jLTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 70, 25));

        btnMetodoPago.setBackground(new java.awt.Color(153, 204, 255));
        btnMetodoPago.setText("Método de pago");
        btnMetodoPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMetodoPagoActionPerformed(evt);
            }
        });
        DatosPelicula.add(btnMetodoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 120, 30));

        jPanel1.add(DatosPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 270, 250));

        btnVolverC1.setBackground(new java.awt.Color(153, 204, 255));
        btnVolverC1.setText("Volver");
        btnVolverC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverC1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolverC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 20));

        jLbPelicula1.setForeground(new java.awt.Color(255, 255, 255));
        jLbPelicula1.setText("Pelicula1");
        jLbPelicula1.setToolTipText("");
        jPanel1.add(jLbPelicula1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 140, 180));

        infPelicula.setForeground(new java.awt.Color(255, 255, 255));
        infPelicula.setText("Informacion de la pelicula");
        jPanel1.add(infPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, 160, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 380));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMetodoPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMetodoPagoActionPerformed
//        frmInicioSesionCliente regresar = new frmInicioSesionCliente();
//        regresar.setVisible(true);
//        this.dispose();
    }//GEN-LAST:event_btnMetodoPagoActionPerformed

    private void btnVolverC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverC1ActionPerformed
        
    }//GEN-LAST:event_btnVolverC1ActionPerformed

    /**
     * @param args the command line arguments
     */
 /*   public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
   /*     try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmResumenCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmResumenCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmResumenCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmResumenCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    /*    java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmResumenCompra().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DatosPelicula;
    private javax.swing.JButton btnMetodoPago;
    private javax.swing.JButton btnVolverC1;
    private javax.swing.JLabel infPelicula;
    private javax.swing.JLabel jLEntrada;
    private javax.swing.JLabel jLFin;
    private javax.swing.JLabel jLInicio;
    private javax.swing.JLabel jLPeli;
    private javax.swing.JLabel jLTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelHoraFin;
    private javax.swing.JLabel jLabelHoraInicio;
    private javax.swing.JLabel jLabelPelicula;
    private javax.swing.JLabel jLabelTipoEntrada;
    private javax.swing.JLabel jLabelTotalResumenCompra;
    private javax.swing.JLabel jLbPelicula1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
